// examples/with-solid/src/App.jsx
import { createClient, Provider, cacheExchange, fetchExchange } from '@urql/solid';
import PokemonList from './PokemonList';

const client = createClient({
  url: 'https://trygql.formidable.dev/graphql/basic-pokedex',
  exchanges: [cacheExchange, fetchExchange],
});

function App() {
  return (
    <Provider value={client}>
      <PokemonList />
    </Provider>
  );
}

export default App;

// examples/with-svelte/src/App.svelte
<script>
  import { setContextClient, Client, cacheExchange, fetchExchange } from "@urql/svelte";
  import PokemonList from "./PokemonList.svelte";

  setContextClient(new Client({
    url: "https://trygql.formidable.dev/graphql/basic-pokedex",
    exchanges: [cacheExchange, fetchExchange],
  }));
</script>

<PokemonList />
