// examples/with-vue3/src/PokemonList.vue
<template>
  <div>
    <ul v-if="pokemons">
      <li v-for="pokemon in pokemons.pokemons" :key="pokemon.id">
        {{ pokemon.name }}
      </li>
    </ul>
    <button @click="nextPage">Next Page</button>
  </div>
</template>

<script>
import { ref, computed } from 'vue';
import { gql, useQuery } from '@urql/vue';

export default {
  async setup() {
    const skip = ref(0);

    const pokemons = await useQuery({
      query: gql`
        query ($skip: Int!) {
          pokemons(limit: 10, skip: $skip) {
            id
            name
          }
        }
      `,
      variables: { skip },
    });

    return {
      pokemons: pokemons.data,
      nextPage() {
        skip.value += 10;
      },
    };
  },
  name: 'PokemonList',
};
</script>

// examples/with-svelte/src/PokemonList.svelte
<script>
  import { gql, operationStore, query } from "@urql/svelte";

  const pokemons = operationStore(
    gql`
      query ($skip: Int!) {
        pokemons(limit: 10, skip: $skip) {
          id
          name
        }
      }
    `,
    { skip: 0 }
  );

  query(pokemons);

  function nextPage() {
    $pokemons.variables = { skip: $pokemons.variables.skip + 10 };
  }
</script>

<div>
  {#if $pokemons.fetching}
    Loading...
  {:else if $pokemons.error}
    Oh no... {$pokemons.error.message}
  {:else}
    <ul>
      {#each $pokemons.data.pokemons as pokemon}
        <li>{pokemon.name}</li>
      {/each}
    </ul>
  {/if}
  <button on:click={nextPage}>Next Page</button>
</div>
