// examples/with-react/src/PokemonList.jsx
import React from 'react';
import { gql, useQuery } from 'urql';

const POKEMONS_QUERY = gql`
  query Pokemons {
    pokemons(limit: 10) {
      id
      name
    }
  }
`;

const PokemonList = () => {
  const [result] = useQuery({ query: POKEMONS_QUERY });

  const { data, fetching, error } = result;

  return (
    <div>
      {fetching && <p>Loading...</p>}

      {error && <p>Oh no... {error.message}</p>}

      {data && (
        <ul>
          {data.pokemons.map(pokemon => (
            <li key={pokemon.id}>{pokemon.name}</li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default PokemonList;

// examples/with-solid/src/PokemonList.jsx
import { Suspense, For } from 'solid-js';
import { gql } from '@urql/core';
import { createQuery } from '@urql/solid';

const POKEMONS_QUERY = gql`
  query Pokemons {
    pokemons(limit: 10) {
      id
      name
    }
  }
`;

const PokemonList = () => {
  const [result] = createQuery({ query: POKEMONS_QUERY });

  return (
    <div>
      <h1>Pokemon List</h1>
      <Suspense fallback={<p>Loading...</p>}>
        <ul>
          <For each={result.data?.pokemons}>
            {pokemon => <li>{pokemon.name}</li>}
          </For>
        </ul>
      </Suspense>
    </div>
  );
};

export default PokemonList;
