// examples/with-svelte/src/App.svelte
<script>
  import { setContextClient, Client, cacheExchange, fetchExchange } from "@urql/svelte";
  import PokemonList from "./PokemonList.svelte";

  setContextClient(new Client({
    url: "https://trygql.formidable.dev/graphql/basic-pokedex",
    exchanges: [cacheExchange, fetchExchange],
  }));
</script>

<PokemonList />

// examples/with-react-native/App.js
import React from 'react';
import { Client, Provider, cacheExchange, fetchExchange } from 'urql';

import PokemonList from './src/screens/PokemonList';

const client = new Client({
  url: 'https://trygql.formidable.dev/graphql/basic-pokedex',
  exchanges: [cacheExchange, fetchExchange],
});

const App = () => {
  return (
    <Provider value={client}>
      <PokemonList />
    </Provider>
  );
};

export default App;
