// examples/with-react/src/App.jsx
import React from 'react';
import { Client, Provider, cacheExchange, fetchExchange } from 'urql';

import PokemonList from './PokemonList';

const client = new Client({
  url: 'https://trygql.formidable.dev/graphql/basic-pokedex',
  exchanges: [cacheExchange, fetchExchange],
});

function App() {
  return (
    <Provider value={client}>
      <PokemonList />
    </Provider>
  );
}

export default App;

// examples/with-vue3/src/App.vue
<template>
  <Suspense>
    <template #default>
      <PokemonList />
    </template>
    <template #fallback>
      <div>Loading...</div>
    </template>
  </Suspense>
</template>

<script>
import { provideClient, cacheExchange, fetchExchange } from '@urql/vue';
import PokemonList from './PokemonList.vue';

export default {
  name: 'App',
  setup() {
    provideClient({
      url: 'https://trygql.formidable.dev/graphql/basic-pokedex',
      exchanges: [cacheExchange, fetchExchange],
    });
  },
  components: {
    PokemonList,
  },
};
</script>
